# Generated by Django 3.2.9 on 2021-11-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aficionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Nacimiento', models.DateField()),
                ('Aficion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raza', models.CharField(max_length=200)),
                ('Nro_Patas', models.IntegerField()),
                ('Dieta', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Nacimiento', models.DateField()),
                ('Especializacion', models.CharField(max_length=50)),
                ('Es_Fotografo', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pato',
        ),
    ]
