# Generated by Django 3.2.9 on 2021-11-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211129_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='aficionado',
            name='Es_Fotografo',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='cientifico',
            name='Es_Fotografo',
            field=models.BooleanField(default=0),
        ),
    ]
